-- Run in the Supabase SQL Editor before deploying Render.
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role varchar(20) NOT NULL DEFAULT 'client' CHECK (role IN ('admin', 'moderator', 'client')),
    profile_picture varchar(255) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    parent_id bigint REFERENCES public.categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.contents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    description text NOT NULL DEFAULT '',
    file_path varchar(255) NOT NULL,
    file_type varchar(20) NOT NULL,
    category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
    uploader_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    download_count integer NOT NULL DEFAULT 0,
    uploaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.content_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    content_title varchar(200) NOT NULL,
    category_requested varchar(100) NOT NULL,
    message text NOT NULL DEFAULT '',
    requester_ip varchar(45),
    session_id varchar(64),
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'fulfilled', 'rejected')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contents_category_id_idx ON public.contents(category_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON public.users(lower(email));
CREATE INDEX IF NOT EXISTS contents_uploader_id_idx ON public.contents(uploader_id);
CREATE INDEX IF NOT EXISTS content_requests_user_id_idx ON public.content_requests(user_id);

-- The PHP server connects directly to PostgreSQL; public API access is not needed.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_requests ENABLE ROW LEVEL SECURITY;

INSERT INTO public.categories (name)
SELECT name FROM (VALUES ('Software'), ('Videos'), ('Documents'), ('Archives'), ('Music'), ('Images')) AS seed(name)
WHERE NOT EXISTS (SELECT 1 FROM public.categories);
